## Assignment No : 3

### NumPy (Set 1)

In [1]:
import numpy as np

In [2]:
# • Create a 3×3 array of all True Boolean values

arr=np.full(9,True).reshape(3,3)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
# •	Extract odd numbers from an array

arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
arr[arr%2==1]

array([ 5,  7,  9, 11, 13, 15])

In [5]:
# •	Replace all odd numbers with -1

arr[arr%2==1]=-1
arr

array([[-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [6]:
# •	Reverse columns of a 2D array

arr=np.arange(5,17).reshape(3,4)
rev=np.flip(arr,axis=1)
rev

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [7]:
# •	Get indices of elements greater than 5 [hint: check where method of numpy]

arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[4, 9, 8],
       [5, 2, 1],
       [1, 1, 3]], dtype=int32)

In [8]:
row,col=np.where(arr>5)
np.stack((row,col),axis=1)

array([[0, 1],
       [0, 2]])

In [9]:
# •	Access last row - last column

arr

array([[4, 9, 8],
       [5, 2, 1],
       [1, 1, 3]], dtype=int32)

In [10]:
last=arr[-1,-1]
last

np.int32(3)

### NumPy (Set 2)

In [11]:
# • Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

arr

array([[4, 9, 8],
       [5, 2, 1],
       [1, 1, 3]], dtype=int32)

In [12]:
min_val = np.min(arr)
max_val = np.max(arr)
normalized_arr = (arr - min_val) / (max_val - min_val)
normalized_arr

array([[0.375, 1.   , 0.875],
       [0.5  , 0.125, 0.   ],
       [0.   , 0.   , 0.25 ]])

In [13]:
arr.flatten()

array([4, 9, 8, 5, 2, 1, 1, 1, 3], dtype=int32)

In [14]:
# • Create a 5×5 array with 1 on border and 0 inside

arr=np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
out = np.pad(arr, pad_width=1, constant_values=1)
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# • Create a random array of 10×10: perform stats (min, max, mean, std)

arr1=np.random.random([10,10])
arr1

array([[5.59385170e-01, 7.05365371e-01, 9.55957591e-01, 2.12120277e-01,
        5.51032854e-01, 1.31957564e-01, 3.47670303e-01, 2.56135256e-01,
        7.42286495e-01, 1.36807654e-01],
       [8.01665801e-01, 7.39147415e-01, 2.47723424e-01, 6.47594101e-01,
        3.89469373e-01, 9.22268429e-01, 5.41543494e-01, 4.34524823e-01,
        4.34539397e-01, 8.01879972e-01],
       [1.74341562e-03, 6.42794030e-01, 8.74714330e-01, 5.70197515e-01,
        5.99350500e-01, 2.30194705e-01, 8.07528748e-01, 7.39158604e-01,
        6.12429782e-01, 2.86890773e-01],
       [7.99121640e-01, 9.91902499e-01, 1.44808609e-01, 9.11729506e-01,
        7.13663745e-01, 8.11912448e-01, 3.55877458e-02, 6.47544579e-01,
        8.99283087e-01, 7.32271325e-01],
       [9.23213654e-01, 8.29129502e-03, 4.70934111e-01, 8.15306770e-03,
        9.14254370e-01, 8.37887365e-01, 1.34956192e-01, 8.26563894e-01,
        8.73902137e-01, 1.96712713e-01],
       [9.16624479e-01, 6.49773014e-01, 8.33941116e-01, 5.95052396e-01,
   

In [17]:
np.min(arr1)

np.float64(0.0003955104004007559)

In [18]:
np.max(arr1)

np.float64(0.9919024992016201)

In [19]:
np.mean(arr1)

np.float64(0.5269131104827272)

In [20]:
np.std(arr1)

np.float64(0.2965144702687128)

In [21]:
# • Broadcast a 1D array over a 2D array [all possible scenarios]

arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
arr2=np.array([1,3,5,6])
arr2

array([1, 3, 5, 6])

In [23]:
arr+arr2

array([[ 6,  9, 12, 14],
       [10, 13, 16, 18],
       [14, 17, 20, 22]])

In [24]:
arr3=np.array([[4],[5],[6]])
arr3

array([[4],
       [5],
       [6]])

In [25]:
arr+arr3

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [19, 20, 21, 22]])

In [26]:
# •	Sort a 2D array by column 1 [hint: check method argsort()]

arr=np.random.randint(10,22,9).reshape(3,3)
arr

array([[15, 21, 18],
       [21, 13, 10],
       [11, 17, 12]], dtype=int32)

In [27]:
sort = arr[arr[:,1].argsort()]
sort

array([[21, 13, 10],
       [11, 17, 12],
       [15, 21, 18]], dtype=int32)

### NumPy (Set 3)

In [28]:
# • Find common elements between two arrays [with and without using intersect1d, use isin() instead]

arr1 = np.array([0, 10, 20, 40, 60, 10])
arr2 = np.array([10, 30, 40, 50])
arr1

array([ 0, 10, 20, 40, 60, 10])

In [29]:
arr2

array([10, 30, 40, 50])

In [30]:
#Intersected

common = np.intersect1d(arr1,arr2)
common

array([10, 40])

In [31]:
mask=np.isin(arr1, arr2)
mask

array([False,  True, False,  True, False,  True])

In [32]:
common=arr1[mask]
unique=np.unique(common)
unique

array([10, 40])

In [33]:
# • Subtract row mean from each row of a 2D array

arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
r_mean=arr.mean(axis=1,keepdims=True)
new_arr=arr-r_mean
new_arr

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [35]:
# • Given a 4×4 array, swap the first half rows with the second half rows

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
arr = np.roll(arr,2,axis=0)
arr

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [37]:
# • Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead)

arr=np.random.randint(10,42,9).reshape(3,3)
arr

array([[32, 29, 10],
       [14, 41, 41],
       [22, 18, 20]], dtype=int32)

In [38]:
idx = np.argsort(arr, axis=None)
sorted_arr = arr.flatten()[idx]

n = 5
res = sorted_arr[-n:]
res

array([22, 29, 32, 41, 41], dtype=int32)

In [39]:
#From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method)

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [40]:
unique_rows = np.unique(arr, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])